export const SETTING_TICKERS = 'tickers'
export const SETTING_TICKER_LABELS = 'tickerLabels'
export const SETTING_SHOW_REFRESH_BUTTON = 'showRefreshButton'

export const EXTREME_GREED = 'extreme greed'
export const GREED = 'greed'
export const NEUTRAL = 'neutral'
export const FEAR = 'fear'
export const EXTREME_FEAR = 'extreme fear'

export const POSITIVE = 'positive'
export const NEGATIVE = 'negative'
export const ZERO = 'zero'

export const DEFAULT_TICKER_1 = 'BTC-USD'
export const DEFAULT_TICKER_2 = 'ETH-USD'
export const DEFAULT_TICKER_3 = 'THB=x'
export const DEFAULT_TICKER_4 = 'NFLX'
export const DEFAULT_TICKER_5 = 'DIA'
export const DEFAULT_TICKER_6 = 'VOO'
